[package]
name = "gazzetta"
version = "0.0.1"
edition = "2021"
description = "An opinionated static site generator for blogs"

[dependencies]
anyhow = "1.0.56"
image = "0.24.3"
chrono = "0.4.22"
date-range = "0.2.2"
serde = { version = "1.0.136", features = ["derive"] }
pulldown-cmark = "0.9.2"
clap = "4.0.10"